name: freerpd
description: A sample command-line application.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {http_multi_server: ^3.2.1, shelf: ^1.3.2, shelf_router: ^1.1.3, shelf_static: ^1.1.1}
